from __future__ import annotations

from pathlib import Path


DEFAULT_INTERVAL_SECONDS = 60
DEFAULT_SCENE_THRESHOLD = 0.35
DEFAULT_OUTPUT_ROOT = Path("output") / "youtube"
OUTPUT_VERSION = "1.0.1"
ANALYSIS_VERSION = OUTPUT_VERSION
SUBTITLE_LANGUAGE_PREFERENCE = (
    "zh-tw",
    "zh-hant",
    "zh-hk",
    "zh-cn",
    "zh-hans",
    "zh",
    "en",
    "en-us",
)
YOUTUBE_HOST_MARKERS = ("youtube.com", "youtu.be", "m.youtube.com")

DEFAULT_TRIAGE_MODE = "on"
DEFAULT_OCR_MODE = "auto"
DEFAULT_BURNED_SUBTITLES_MODE = "auto"
DEFAULT_GPT_MODE = "off"
DEFAULT_REVIEW_MODE = "interactive"
DEFAULT_GPT_MODEL = "gpt-5.4"
DEFAULT_REPORT_LANGUAGE = "zh-TW"
DEFAULT_ARTIFACTS_MODE = "minimal"

# These defaults are intentionally provisional. They are centralized here so
# calibration can tune them later without rewriting the rule logic.
DEFAULT_BLUR_REJECTION_VARIANCE = 100.0
DEFAULT_PHASH_DUPLICATE_DISTANCE = 6
DEFAULT_SLIDE_OCR_CHAR_COUNT = 40
DEFAULT_DENSE_SLIDE_OCR_CHAR_COUNT = 120
DEFAULT_TALKING_HEAD_OCR_CHAR_MAX = 20
DEFAULT_CHART_NUMERIC_RATIO = 0.20
DEFAULT_CHART_HINT_THRESHOLD = 0.60
DEFAULT_MOTION_LOW_THRESHOLD = 0.08
DEFAULT_MOTION_HIGH_THRESHOLD = 0.18
DEFAULT_SEGMENT_MERGE_GAP_SECONDS = 12.0
DEFAULT_TRANSCRIPT_CONTEXT_PADDING_SECONDS = 5.0
DEFAULT_REVIEW_CONFIDENCE_THRESHOLD = 0.75
DEFAULT_AUTO_APPROVE_CONFIDENCE = 0.82

# These burned-subtitle OCR defaults are intentionally provisional and kept
# centralized for fixture-driven tuning.
DEFAULT_BURNED_SUBTITLE_SAMPLE_FPS = 1.0
DEFAULT_BURNED_SUBTITLE_AUTO_SAMPLE_FPS = 0.5
DEFAULT_BURNED_SUBTITLE_PROBE_DURATION_SECONDS = 20.0
DEFAULT_BURNED_SUBTITLE_PROBE_SAMPLES = 8
DEFAULT_BURNED_SUBTITLE_PROBE_MIN_HITS = 3
DEFAULT_BURNED_SUBTITLE_PROBE_MIN_DISTINCT_TEXTS = 2
DEFAULT_BURNED_SUBTITLE_AUTO_PROBE_MIN_HITS = 4
DEFAULT_BURNED_SUBTITLE_AUTO_PROBE_MIN_DISTINCT_TEXTS = 3
DEFAULT_BURNED_SUBTITLE_BAND_HEIGHT_RATIO = 0.16
DEFAULT_BURNED_SUBTITLE_SIDE_MARGIN_RATIO = 0.08
DEFAULT_BURNED_SUBTITLE_DETECTION_WIDTH_RATIO = 0.70
DEFAULT_BURNED_SUBTITLE_DETECTION_HEIGHT_RATIO = 0.60
DEFAULT_BURNED_SUBTITLE_DIFF_THRESHOLD = 0.06
DEFAULT_BURNED_SUBTITLE_QUICK_REJECT_SECONDS = 8.0
DEFAULT_BURNED_SUBTITLE_QUICK_REJECT_EVENTS = 4
DEFAULT_BURNED_SUBTITLE_AUTO_QUICK_REJECT_SECONDS = 4.0
DEFAULT_BURNED_SUBTITLE_AUTO_QUICK_REJECT_EVENTS = 2
DEFAULT_BURNED_SUBTITLE_QUICK_MIN_NONEMPTY_HITS = 2
DEFAULT_BURNED_SUBTITLE_QUICK_MIN_VISIBLE_CHARS = 6.0
DEFAULT_BURNED_SUBTITLE_QUICK_MIN_CJK_RATIO = 0.45
DEFAULT_BURNED_SUBTITLE_QUICK_MAX_NOISE_RATIO = 0.35
DEFAULT_BURNED_SUBTITLE_EARLY_GATE_SECONDS = 30.0
DEFAULT_BURNED_SUBTITLE_EARLY_GATE_EVENTS = 12
DEFAULT_BURNED_SUBTITLE_AUTO_EARLY_GATE_SECONDS = 10.0
DEFAULT_BURNED_SUBTITLE_AUTO_EARLY_GATE_EVENTS = 4
DEFAULT_BURNED_SUBTITLE_MIN_NONEMPTY_HITS = 4
DEFAULT_BURNED_SUBTITLE_MIN_HIT_RATE = 0.40
DEFAULT_BURNED_SUBTITLE_MIN_CJK_CHARS = 40
DEFAULT_BURNED_SUBTITLE_MIN_CJK_RATIO = 0.50
DEFAULT_BURNED_SUBTITLE_AUTO_MIN_NONEMPTY_HITS = 2
DEFAULT_BURNED_SUBTITLE_AUTO_MIN_HIT_RATE = 0.50
DEFAULT_BURNED_SUBTITLE_AUTO_MIN_CJK_CHARS = 20
DEFAULT_BURNED_SUBTITLE_AUTO_MIN_CJK_RATIO = 0.60
DEFAULT_BURNED_SUBTITLE_MIN_VISIBLE_CHARS = 6
DEFAULT_BURNED_SUBTITLE_MAX_NOISE_RATIO = 0.35
DEFAULT_BURNED_SUBTITLE_UPSCALE_HEIGHT_THRESHOLD = 180
DEFAULT_BURNED_SUBTITLE_MAX_UPSCALE = 1.5
BURNED_SUBTITLE_TESSERACT_LANGS = ("chi_sim", "chi_tra")
BURNED_SUBTITLE_OPTIONAL_TESSERACT_LANGS = ("eng",)

MODEL_PREFIXES_SUPPORTING_ORIGINAL = ("gpt-5",)
GPT_PROMPT_LABELS = ("slides", "chart_table", "uncertain")
ROUTING_LABELS = ("slides", "chart_table", "talking_head", "b_roll", "uncertain")
